#!/bin/bash
# Puts a "GitMir Local" app on your Desktop.
#
# Double-clicking start.command works, but it keeps a Terminal window open and the
# server dies when you close it. This builds a small .app instead: it starts the
# dashboard in the background if it is not already running, waits for it, and opens
# your browser. Close everything afterwards — the dashboard keeps running.
#
# Run it once:  double-click this file, or  bash install-shortcut.command
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="GitMir Local"
APP="$HOME/Desktop/$APP_NAME.app"
PORT="${GITMIR_PORT:-4599}"   # same override the server honours
URL="http://localhost:$PORT"

# A GUI-launched app does not inherit your shell's PATH, so resolve node now and bake
# the absolute path into the launcher.
NODE="$(command -v node || true)"
if [ -z "$NODE" ]; then
  for p in /usr/local/bin/node /opt/homebrew/bin/node /usr/bin/node "$HOME/.volta/bin/node"; do
    [ -x "$p" ] && NODE="$p" && break
  done
fi
if [ -z "$NODE" ]; then
  echo "Could not find node. Install Node.js 18+ (22+ if you want the Team bridge) and run this again."
  exit 1
fi
echo "node:      $NODE ($("$NODE" -v))"
echo "dashboard: $DIR"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>com.gitmir.claudecontrol.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSUIElement</key><true/>
</dict></plist>
PLIST

cat > "$APP/Contents/MacOS/launch" <<LAUNCH
#!/bin/bash
# Generated by install-shortcut.command — paths are baked in on purpose.
DIR="$DIR"
NODE="$NODE"
URL="$URL"
LOG="\$HOME/Library/Logs/gitmir-local.log"

# Already up? Just show it.
if curl -s --max-time 2 "\$URL/api/ping" >/dev/null 2>&1; then
  open "\$URL"; exit 0
fi

cd "\$DIR" || { osascript -e 'display alert "GitMir Local" message "The project folder has moved. Run install-shortcut.command again."'; exit 1; }
mkdir -p "\$(dirname "\$LOG")"
# nohup + disown: the dashboard outlives this launcher and anything you close.
GITMIR_PORT="$PORT" nohup "\$NODE" server.ts >>"\$LOG" 2>&1 &
disown 2>/dev/null || true

for i in \$(seq 1 60); do
  curl -s --max-time 1 "\$URL/api/ping" >/dev/null 2>&1 && { open "\$URL"; exit 0; }
  sleep 0.25
done

osascript -e 'display alert "GitMir Local" message "The dashboard did not start. See ~/Library/Logs/gitmir-local.log"'
exit 1
LAUNCH
chmod +x "$APP/Contents/MacOS/launch"

# Icon from the bundled mark, if the tools are there. Not fatal if they are not.
if [ -f "$DIR/vendor/gitmir-mark.svg" ] && command -v qlmanage >/dev/null 2>&1; then
  TMP="$(mktemp -d)"
  if qlmanage -t -s 1024 -o "$TMP" "$DIR/vendor/gitmir-mark.svg" >/dev/null 2>&1 && [ -f "$TMP"/*.png ]; then
    SRC="$(ls "$TMP"/*.png | head -1)"
    ICONSET="$TMP/icon.iconset"; mkdir -p "$ICONSET"
    for s in 16 32 64 128 256 512; do
      sips -z $s $s "$SRC" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null 2>&1
      sips -z $((s*2)) $((s*2)) "$SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
    done
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/icon.icns" >/dev/null 2>&1 || true
  fi
  rm -rf "$TMP"
fi

touch "$APP"   # make Finder pick up the new bundle
echo
echo "Done — \"$APP_NAME\" is on your Desktop."
echo "Double-click it: the dashboard starts in the background and your browser opens at $URL."
echo "It keeps running after you close the browser. To stop it:  pkill -f 'node server.ts'"
